---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: dc03d89f9f228a9e2bcb238b0ebd91d85ed44250
      fabric8.io/git-branch: master
    labels:
      provider: fabric8
      project: karaf2-camel-test-rest2
      version: 1.0.1-SNAPSHOT
      group: io.fabric8.quickstarts
    name: karaf2-camel-test-rest2
  spec:
    ports:
    - name: intermapper
      port: 8181
      protocol: TCP
      targetPort: 8181
    selector:
      project: karaf2-camel-test-rest2
      provider: fabric8
      group: io.fabric8.quickstarts
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: dc03d89f9f228a9e2bcb238b0ebd91d85ed44250
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=karaf2-camel-test-rest2&var-version=1.0.1-SNAPSHOT
    labels:
      provider: fabric8
      project: karaf2-camel-test-rest2
      version: 1.0.1-SNAPSHOT
      group: io.fabric8.quickstarts
    name: karaf2-camel-test-rest2
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: karaf2-camel-test-rest2
        provider: fabric8
        group: io.fabric8.quickstarts
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: dc03d89f9f228a9e2bcb238b0ebd91d85ed44250
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=karaf2-camel-test-rest2&var-version=1.0.1-SNAPSHOT
        labels:
          provider: fabric8
          project: karaf2-camel-test-rest2
          version: 1.0.1-SNAPSHOT
          group: io.fabric8.quickstarts
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: karaf2-camel-test-rest2:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8181
            initialDelaySeconds: 180
          name: karaf
          ports:
          - containerPort: 8181
            name: intermapper
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness-check
              port: 8181
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 128Mi
          securityContext:
            privileged: false
