---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: spring-boot-test-rest-camel
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: spring-boot-test-rest-camel@sha256:7268640f7bc0002f0f848c792bfcafe0342d60321a32b6636a12988fe6f75013
        namespace: test2-hc
      name: latest
