---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 0f597d83c591827d2f472e493ec7562ff3ac4aa1
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: spring-boot-test-rest-camel
      provider: fabric8
      version: 1.0.1-SNAPSHOT
      group: io.fabric8.quickstarts
    name: spring-boot-test-rest-camel
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-test-rest-camel
      provider: fabric8
      group: io.fabric8.quickstarts
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 0f597d83c591827d2f472e493ec7562ff3ac4aa1
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=spring-boot-test-rest-camel&var-version=1.0.1-SNAPSHOT
    labels:
      app: spring-boot-test-rest-camel
      provider: fabric8
      version: 1.0.1-SNAPSHOT
      group: io.fabric8.quickstarts
    name: spring-boot-test-rest-camel
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: spring-boot-test-rest-camel
        provider: fabric8
        group: io.fabric8.quickstarts
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 0f597d83c591827d2f472e493ec7562ff3ac4aa1
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=spring-boot-test-rest-camel&var-version=1.0.1-SNAPSHOT
        labels:
          app: spring-boot-test-rest-camel
          provider: fabric8
          version: 1.0.1-SNAPSHOT
          group: io.fabric8.quickstarts
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: spring-boot-test-rest-camel:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
